services:
  game:
    build: .
    image: crystall-island-server
    container_name: crystall-island-server
    env_file:
      - .env.prod
    volumes:
      - ./EngageAI-NLEPrototype:/app/EngageAI-NLEPrototype
    ports:
      - 9000:9000