name: Deploy to Jetstream

on:
  push:
    branches:
      - main

  schedule:
    - cron: '0 0 * * *' # Run every day at 00:00 UTC

jobs:
  DeployToEC2:
    name: Deploy Crystall Island to JetStream2 (Dev/Prod)
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - name: Build and Deploy (crystall-island.syncflow.live)
        if: github.event_name == 'push'
        env:
          PRIVATE_KEY: ${{ secrets.JETSTREAM2_PRIV_KEY_PEM }}
          HOST: ${{ secrets.JETSTREAM2_HOST }}
          USERNAME: ${{ secrets.JETSTREAM2_USERNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh-keygen -y -f private_key > /dev/null
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOST} '
            cd $HOME/CrystallIslandDeployment
            rm -rf crystall-island-server
            git clone git@github.com:oele-isis-vanderbilt/crystall-island-server.git 
            cp .env crystall-island-server/.env.prod
            cp -r EngageAI-NLEPrototype crystall-island-server/EngageAI-NLEPrototype
            docker compose -p crystall-island-server -f crystall-island-server/docker-compose.yml build
            docker compose -p crystall-island-server -f crystall-island-server/docker-compose.yml down
            docker compose -p crystall-island-server -f crystall-island-server/docker-compose.yml up -d
          '